// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezpzyhnzcoonwytpfcla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6cHp5aG56Y29vbnd5dHBmY2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjQ2MDAsImV4cCI6MjA3MDg0MDYwMH0.bhwSQ8p6_iG-i8zcXr5Gc8gTR4ZNZ0_nqiYrcKfrJkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});